In [16]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\mituc\Python\attack_classifier\data\df_attacks.csv")
df.drop(columns=['Unnamed: 0'], inplace=True)

In [4]:
df.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,num_failed_logins,...,serror_rate,rerror_rate,same_srv_rate,diff_srv_rate,srv_diff_host_rate,dst_host_count,dst_host_diff_srv_rate,dst_host_srv_diff_host_rate,target,Attack Type
0,0,tcp,http,SF,181,5450,0,0,0,0,...,0.0,0.0,1.0,0.0,0.0,9,0.0,0.0,normal.,normal
1,0,tcp,http,SF,239,486,0,0,0,0,...,0.0,0.0,1.0,0.0,0.0,19,0.0,0.0,normal.,normal
2,0,tcp,http,SF,235,1337,0,0,0,0,...,0.0,0.0,1.0,0.0,0.0,29,0.0,0.0,normal.,normal
3,0,tcp,http,SF,219,1337,0,0,0,0,...,0.0,0.0,1.0,0.0,0.0,39,0.0,0.0,normal.,normal
4,0,tcp,http,SF,217,2032,0,0,0,0,...,0.0,0.0,1.0,0.0,0.0,49,0.0,0.0,normal.,normal

In [5]:
df['protocol_type'].value_counts()

icmp    283602
tcp     190065
udp      20354
Name: protocol_type, dtype: int64

In [6]:
#protocol_type feature mapping
pmap = {'icmp':0,'tcp':1,'udp':2}
df['protocol_type'] = df['protocol_type'].map(pmap)

In [7]:
df['flag'].value_counts()

SF        378440
S0         87007
REJ        26875
RSTR         903
RSTO         579
SH           107
S1            57
S2            24
RSTOS0        11
S3            10
OTH            8
Name: flag, dtype: int64

In [8]:
#flag feature mapping
fmap = {'SF':0,'S0':1,'REJ':2,'RSTR':3,'RSTO':4,'SH':5 ,'S1':6 ,'S2':7,'RSTOS0':8,'S3':9 ,'OTH':10}
df['flag'] = df['flag'].map(fmap)

In [9]:
df.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,num_failed_logins,...,serror_rate,rerror_rate,same_srv_rate,diff_srv_rate,srv_diff_host_rate,dst_host_count,dst_host_diff_srv_rate,dst_host_srv_diff_host_rate,target,Attack Type
0,0,1,http,0,181,5450,0,0,0,0,...,0.0,0.0,1.0,0.0,0.0,9,0.0,0.0,normal.,normal
1,0,1,http,0,239,486,0,0,0,0,...,0.0,0.0,1.0,0.0,0.0,19,0.0,0.0,normal.,normal
2,0,1,http,0,235,1337,0,0,0,0,...,0.0,0.0,1.0,0.0,0.0,29,0.0,0.0,normal.,normal
3,0,1,http,0,219,1337,0,0,0,0,...,0.0,0.0,1.0,0.0,0.0,39,0.0,0.0,normal.,normal
4,0,1,http,0,217,2032,0,0,0,0,...,0.0,0.0,1.0,0.0,0.0,49,0.0,0.0,normal.,normal

In [10]:
df.drop('service',axis = 1,inplace= True)

In [11]:
df.shape

(494021, 30)

In [13]:
df.dtypes

duration                         int64
protocol_type                    int64
flag                             int64
src_bytes                        int64
dst_bytes                        int64
land                             int64
wrong_fragment                   int64
urgent                           int64
num_failed_logins                int64
logged_in                        int64
num_compromised                  int64
root_shell                       int64
su_attempted                     int64
num_file_creations               int64
num_shells                       int64
num_access_files                 int64
num_outbound_cmds                int64
is_host_login                    int64
is_guest_login                   int64
srv_count                        int64
serror_rate                    float64
rerror_rate                    float64
same_srv_rate                  float64
diff_srv_rate                  float64
srv_diff_host_rate             float64
dst_host_count                   int64
dst_host_diff_srv_rate         float64
dst_host_srv_diff_host_rate    float64
target                          object
Attack Type                     object
dtype: object

In [14]:
df.drop(['target'], axis=1, inplace=True)

In [17]:
df.to_csv(r"data\df_attacks_enc.csv")